const headers = [
  "Usuario Id",
  "Alumno Id",
  "Nombre",
  "Estudio",
  "Curso",
  "Grupo",
  "start",
  "end",
  "dia",
  "redes1",
  "redes2",
  "beliefs1",
  "beliefs2",
  "popular",
  "central",
  "conocidos",
  "otros",
  "eayuda",
  "ayuda",
  "circunstancia",
  "personal",
  "alone",
  "fun",
  "general",
  "uce",
  "siblings",
  "brothers",
  "sisters",
  "posicion",
  "Organización del tiempo",
  "Te has apuntado a actividades",
  "Carga de trabajo",
  "dificultad",
  "asignaturas",
  "motivoasig",
  "motivoasig1",
  "abandono",
  "motivoabandono",
  "motivoabandono1",
];
const log = (value) => "2026-10-05 09:00:00 -> " + value;
const row = (values) => headers.map((h) => values[h] ?? null);
function fixture() {
  return [
    headers,
    row({
      "Usuario Id": "S01",
      "Alumno Id": 1001,
      Nombre: "Persona Prueba",
      Estudio: 1,
      Curso: "PSI",
      Grupo: "A",
      start: log(""),
      end: log(""),
      dia: log("Par"),
      redes1: log("1002 (Buena relación)"),
      beliefs1: log("1002 (Buena relación)"),
      ayuda: log("1002"),
      circunstancia: log("Historia sintética\n<img src=x onerror=alert(1)>"),
      alone: log("Nunca"),
      fun: log("Siempre"),
      general: log("Casi siempre"),
      abandono: log("No"),
    }),
    row({
      "Usuario Id": "S02",
      "Alumno Id": 1002,
      Nombre: "Persona Prueba",
      Estudio: 1,
      Curso: "PSI",
      Grupo: "A",
      start: log(""),
      dia: log("Impar"),
      redes2: log("1001 (Buena relación)"),
      ayuda: log("Nadie"),
      alone: log("Siempre"),
    }),
    row({
      "Usuario Id": "S03",
      "Alumno Id": 1003,
      Estudio: 1,
      Curso: "ENF",
      Grupo: "B",
    }),
  ];
}
module.exports = { headers, log, row, fixture };
